[package]
name = "twitch-player"
version = "0.1.0"
authors = ["Guillaume Depardon <guillaume.depardon@gmail.com>"]

[dependencies]
winapi = { version = "0.3.4", features = ["winuser"] }

futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
tokio-timer = "0.1"
