[package]
name = "twitchd"
version = "0.1.0"
authors = ["Guillaume Depardon <guillaume.depardon@gmail.com>"]

[dependencies]
futures = "0.1"

hyper = "0.11"
hyper-tls = "0.1"
url = "1.7"

tokio-core = "0.1"
tokio-timer = "0.1"
tokio-tls = "0.1"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

num_cpus = "1.8"

nom = "3.2"

structopt = "0.2"
